#!/bin/bash
#CREADOR Henry Chumo | 06/06/2019
# UPDATE DEFINIDO    | 26/10/2023
# MODIFICADO         | Karl199x

# NUNCA  DEJES DE APRENDER
# POWER BY Karl199x

# -*- ENCODING: UTF-8 -*-
z="
";XUz='Karl199x|Karl199x|Karl199x'
